### ISSUE TITLE
Final release checklist

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#115]
These are a few issues I have identified that need to be addressed before we release.

- [x] Update README   
Note: We can render this from a `README.Rmd` BUT we have to make sure to run it from my dummy account so we don't expose data from a live Dropbox account.
- [x] Write a NEWS file clearly documenting the changes and especially the breaking changes. I suggest one line per function, paying special attention to ones with breaking changes.
- [x] Include install instructions in case CRAN does not update before the 28th
- [x] Add a contributor code of conduct
 - [x]  Add clear instructions for anyone making a PR. That they auth and save a `token.rds` in their tests/testthat folder to test against.
 - [x]  Fix race conditions in the tests (#112)
 - [ ]  After acceptance to CRAN, archive the software on Zenodo and add a DOI badge.
- [x] Preemptively add a `cran-comments.md` explaining why none of the tests will run on CRAN.
- [x]  Do a documentation sweep and explicit spell check to make sure it all reads clearly

**Comment by ClaytonJY** [comment]
- [ ] double-check that all tests have a `skip_on_cran` and don't do _anything_ outside a `test_that` block
- [ ] make sure all milestone-assigned issues have been closed

**Comment by karthik** [comment]
- [x] spell check package.

**Comment by karthik** [comment]
![giphy-downsized-large](https://user-images.githubusercontent.com/138494/30940747-00d59b06-a397-11e7-8ffa-6b5540c1768d.gif)
